#ifndef FIREBASEWRAPPER_GLOBAL_H
#define FIREBASEWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FIREBASEWRAPPER_LIBRARY)
#  define FIREBASEWRAPPER_EXPORT Q_DECL_EXPORT
#else
#  define FIREBASEWRAPPER_EXPORT Q_DECL_IMPORT
#endif

#endif // FIREBASEWRAPPER_GLOBAL_H
